---
name: Build

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - name: Install npm dependencies
        run: npm i -q

      - name: Build
        run: npm run build

      - name: Configure npm credentials
        run: curl --user ${{ secrets.ARTIFACTORY_USERNAME }}:${{ secrets.ARTIFACTORY_PASSWORD }} https://egym.jfrog.io/egym/api/npm/auth > ~/.npmrc

      - name: Publish
        run: npm publish
